### ISSUE TITLE
Can't load a libskype*_x86.so 

### ISSUE THREAD

**Issue by taktos** [taksan/skype-java-api#22]
Hello,
I'm running this on Ubuntu 32bit and got an error below.
```
java.lang.IllegalStateException: Library libskype_x11_skype_x86.so is not in the resource path! This is a bug!
        at com.skype.connector.ConnectorUtils.loadLibrary(ConnectorUtils.java:77)
        at com.skype.connector.linux.SkypeFramework.init(SkypeFramework.java:58)
        at com.skype.connector.linux.LinuxConnector.isRunning(LinuxConnector.java:61)
```
I renamed the 'libskype_x11_x86.so' to 'libskype_x11_skype_x86.so', the error didn't recur.
I think the argument  value on SkypeFramework.java:58 is invalid: `ConnectorUtils.loadLibrary(getLibName("skype_x86"));` would be `ConnectorUtils.loadLibrary(getLibName("x86"));`

**Comment by taksan** [comment]
The actual bug in the issue was fixed. As for the NPE, another issue should be opened to deal with that.
