### ISSUE TITLE
Skype for Java throws exception while using in Group Chat

### ISSUE THREAD

**Issue by sandeeprock12** [taksan/skype-java-api#45]
I have been Skype for Java API successfully in singular chats. But, I am getting an exception while using it in Group Chat. Below is the exception:

com.skype.CommandFailedException: Invalid/uknown chat name given
    at com.skype.Utils.checkError(Utils.java:77)
    at com.skype.Chat.send(Chat.java:275)
    at skypePackage.MyListener.myListener(MyListener.java:85)
    at skypePackage.MyListener.chatMessageReceived(MyListener.java:220)
    at com.skype.ChatMessageConnectorListener.fireMessageReceived(ChatMessageConnectorListener.java:58)
    at com.skype.ChatMessageConnectorListener.messageReceived(ChatMessageConnectorListener.java:38)
    at com.skype.connector.Connector.fireMessageEvent(Connector.java:1119)
    at com.skype.connector.Connector.access$500(Connector.java:37)
    at com.skype.connector.Connector$13.run(Connector.java:1098)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Please help!

**Comment by X-com** [comment]
I have desperately been trying to find a solution for the group chats. When using Skype.getAllChats(); the group chats simply wont show up at all. Anyone know of any workaround? If not even that, any way to downgrade skype to the earliest possible version where group chats can be searched using the api?

Using
jdk 1.8.31
skype 6.20
Windows 7 operating system.

**Comment by Cuniq** [comment]
check my answer [here](https://stackoverflow.com/questions/27931802/sending-skype-messages-in-java-using-the-java-skype-api-by-taskan/28382505#28382505)

**Comment by X-com** [comment]
I did try both methods and neither picked up group chats. There are some older group chats in my contacts list, oddly those it can find but any new group chats created simply are not showing up at all. 

What version of Skype did you test this on? could it also be related to some form of setting?

**Comment by EionRobb** [comment]
You're not going to be able to use the old skype Api with new chat threads
as they're not accessible from the desktop Api. You'd have to implement
msnp24 or use the new skype for web which is in closed beta
