### ISSUE TITLE
Skype Java Api 64bit issue Mac

### ISSUE THREAD

**Issue by HowardStark** [taksan/skype-java-api#56]
When running in IntelliJ on Mac OS X 10.9, it threw the following:

`Exception in thread "main" java.lang.IllegalStateException: The connector couldn't be initialized.
        at com.skype.connector.Connector.getInstance(Connector.java:85)
        at com.skype.Skype.getConnectorInstance(Skype.java:970)
        at com.skype.Skype.setDebug(Skype.java:135)
        at Bot.main(Bot.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.skype.connector.Connector.getInstance(Connector.java:83)
        ... 8 more
Caused by: com.skype.connector.UnsupportedArchitectureException: Skype Java Api doesn't support running under 64bit architectures under Mac OSX. You may try running with 'java -d32' if your system has java 32bit installed.
        at com.skype.connector.osx.OSXConnector.getInstance(OSXConnector.java:48)
        ... 13 more`

I attempted to run it with java -d32, and it just said that 32 bit architecture is not supported in this JVM instance. 

Let me know what I can do!

**Comment by evluhin** [comment]
It means that JVM doesn't work in 32bit mode. So it's not an issue of the API (except that the API doesn't support 64bit). So you'll have to install Windows since Mac doesn't have JVM with support of 32bit.
I also a mac user so I tried a lot.

**Comment by taksan** [comment]
Just like @evluhin commented, the api does't support 64bit (the skype team never released support for 64bit). Because it is deprecated, they never will.

**Comment by tarkik-tatva** [comment]
I am facing same issue. Is there any work around for the same ?
P.S.: I have tried -d32 VM Argument but it didn't work.
