### ISSUE TITLE
API is not working any more - CommandFailedException while recording calls

### ISSUE THREAD

**Issue by tatvaharshal** [taksan/skype-java-api#85]
Hello **@taksan**,

First of all, **Thank you** for the API.

I have been using **skype-java-api** successfully for **call recording**. 
But, now I am getting an **exception** while **recording calls**. 

### Below is the **exception**:
**com.skype.CommandFailedException: ALTER CALL: unable to alter input/output**
	at com.skype.Utils.checkError(Utils.java:77)
	at com.skype.Call.setStreams(Call.java:769)
	at com.skype.Call.setOutputStreams(Call.java:751)
	at com.skype.Call.setFileOutput(Call.java:645)
	at com.tatvasoft.skype.recorder.listners.AudioCallListener.actionPerformed(AudioCallListener.java:116)

	
### Below is the sample **code**:
@Override
public void callMonitor(Call call, Status status) throws SkypeException {

	if(call.getStatus().compareTo(Call.Status.INPROGRESS) == 0) {
		try {
			call.setFileOutput(new File("speaker.mp3"));
			call.setFileCaptureMic(new File("mic.mp3"));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

Although it is **working sometimes** with some versions of Skype for ex. **7.16.0.102, 7.28.0.101 ...**
But it's completely **not working** with latest Skype versions for ex. **7.29.0.101, 7.30.0.103 ...**

OS Details 	: Windows 7, Windows 8, Windows 8.1
Java	   		: jdk1.8.0_51
Skype version	: 7.16.0.102 and above

**Have you dropped all the support for this API?
Is this a reason why I am not able to record calls ?	
Could you please confirm this issue ?**

**TIA**

**Comment by taksan** [comment]
I dropped all support, because Microsoft is phasing out desktop api (which is the basis for this library).

Sorry.

**Comment by tatvaharshal** [comment]
Thank you **@taksan** for your reply.

As we have a well developed desktop application based on this library which is now completely stopped working. 

**Is there any other work around or solution to achieve this ?
If any please help me to find the solution for this.**

**TIA**

**Comment by tatvaharshal** [comment]
Hello Team @taksan,

Please help me, If any suggestion/solution for this issue ?

Is there any other way I can achieve this ?

**Comment by FFY00** [comment]
You can use old versions of skype. Maybe you can also try to interface with skype web but that's all.
